/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wilian.Vistas;
import com.wilian.DAO.CDEstudiantes;
import com.wilian.DataBase.ConexionMYSQL;
import com.wilian.Entidades.DbNotas;
import com.wilian.Entidades.Estudiantes;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.crypto.AEADBadTagException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Willian
 */
public class FrmEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FrmEstudiantes
     */
    public FrmEstudiantes() {
        initComponents();
        CargarEstudiantesTabla();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEstudiantes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        txtEliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnNuevoEstudiante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblEstudiantes.setEditingColumn(0);
        jtblEstudiantes.setEditingRow(0);
        jtblEstudiantes.setName(""); // NOI18N
        jtblEstudiantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jtblEstudiantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEstudiantesMouseClicked(evt);
            }
        });
        jtblEstudiantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblEstudiantesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblEstudiantes);

        jLabel1.setText("CONTROL DE ESTUDIANTES");

        jButton2.setText("Modelaje de TABLA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNotas.setText("Notas de estuiantes");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });

        jButton3.setText("Inscripcion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtEliminar)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotas)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEliminar)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnNuevoEstudiante.setText("Nuevo Estudiante");
        btnNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEstudianteActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione la fila y de click en <<Enter>> para modificar el registro.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(294, 294, 294)
                                .addComponent(btnNuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addComponent(btnNuevoEstudiante))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEstudianteActionPerformed
        JfrmCrudEstudiantes frmCrud  = new JfrmCrudEstudiantes();
        frmCrud.accionCrud = "Crear";
        frmCrud.frmEstudiantes = this;
        frmCrud.setVisible(true);
    }//GEN-LAST:event_btnNuevoEstudianteActionPerformed

    private void jtblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEstudiantesMouseClicked

    }//GEN-LAST:event_jtblEstudiantesMouseClicked

    private void jtblEstudiantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblEstudiantesKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (jtblEstudiantes.getSelectedRowCount() == 1) {
                JfrmCrudEstudiantes frmCrud = new JfrmCrudEstudiantes();
                frmCrud.accionCrud = "Actualizar";
                frmCrud.frmEstudiantes = this;

                int filaSeleccionada = jtblEstudiantes.getSelectedRow();
                frmCrud.txtIdEstudiante.setText(jtblEstudiantes.getValueAt(filaSeleccionada, 0).toString());
                frmCrud.txtNombres.setText(jtblEstudiantes.getValueAt(filaSeleccionada, 1).toString());
                frmCrud.txtApellidos.setText(jtblEstudiantes.getValueAt(filaSeleccionada, 2).toString());

                frmCrud.setVisible(true);
            }
        }
    }//GEN-LAST:event_jtblEstudiantesKeyPressed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        // TODO add your handling code here:
        JfrmNotas jfrmNotas = new JfrmNotas();
        jfrmNotas.setVisible(true);
    }//GEN-LAST:event_btnNotasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargarEstudiantesTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
            if (jtblEstudiantes.getSelectedRowCount() == 1) {
                clsD_estudiantes.EliminarEstudiante(Integer.parseInt(jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 0).toString()));
                CargarEstudiantesTabla();
            }       
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new JfrmInscripcion().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void CargarEstudiantesTabla(){
        // TODO add your handling code here:
        String titulos[] = {"ID","NOMBRES","APELLIDOS"};
        
        //areglos con una dimension especificada
        //double numeros[] = new double[3];
        
        //Manejando las tablas mediante modelo de datos (modelaje de tablas)
        //DefaultTableModel 
        /*modela la tabla con filas y columnas con las dimenciones que le indiquemos*/
        
        DefaultTableModel modeloTabla = new DefaultTableModel(null, titulos);
        
        
        //trayendo datos
        CDEstudiantes clsD_Estudiante = new CDEstudiantes();
        Estudiantes estudiantes = new Estudiantes();
         
        DbNotas nota = new DbNotas();
        
        /*
        //se puede usar el arraylist con un tipo de dato especifico
        //o usando var
        ArrayList<Estudiantes> listadoEstudiantes = ;
        

        //tipo de dato para iterar los datos
        Iterator iterador = listadoEstudiantes.iterator();
        
        //
        String fila[] = new String[4];
        
        //iterar datos
        while(iterador.hasNext()){
            /*convertir la variable de iteracion con los datos agregados,
            se convierte en un tipo de dato por 
            la clase que hemos utilizado*//*
                Estudiantes bucleEstudiante = (Estudiantes)iterador.next();
                fila[0] = String.valueOf(bucleEstudiante.getId());
                fila[1] = bucleEstudiante.getNombres();
                fila[2] = bucleEstudiante.getApellidos();
                modeloTabla.addRow(fila);
                
        }
    */

        //iterando datos con un for each
        String fila[] = new String[4];
        
            for(var i: clsD_Estudiante.MostrarEstudiantes() ){
                //Estudiantes bucleEstudiante = new Estudiantes();
                fila[0] = String.valueOf(i.getId());
                fila[1] = i.getNombres();
                fila[2] = i.getApellidos();
                modeloTabla.addRow(fila);
            } 
        
        //setear modelo
        jtblEstudiantes.setModel(modeloTabla);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstudiantes().setVisible(true);
            }
        });
        
        //mostrar

    }
        CDEstudiantes clsD_estudiantes = new CDEstudiantes();
        
        private void MostrarEstudiantes(){
            ArrayList<Estudiantes> listaEstudiantes = clsD_estudiantes.MostrarEstudiantes();
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnNuevoEstudiante;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jtblEstudiantes;
    private javax.swing.JButton txtEliminar;
    // End of variables declaration//GEN-END:variables
}
